# Reference Projects Configuration for FABulous Testing
# This file defines reference projects to test against FABulous

reference_projects:
  - name: "run_legacy_1.3_verilog_demo"
    path: "./legacy/clean/demo_verilog/"
    language: "verilog"
    test_mode: "run"
    description: "Run legacy FABulous 1.3 Verilog demo project for error checking"
    expected_outputs:
      - "Fabric/eFPGA_top.v"
      - "Fabric/eFPGA.v"
      - "Tile/LUT4AB/LUT4AB.v"
      - "Tile/LUT4AB/LUT4AB_switch_matrix.csv"
      - "Tile/LUT4AB/LUT4AB_switch_matrix.v"
      - "Tile/LUT4AB/LUT4AB_ConfigMem.csv"
      - "Tile/LUT4AB/LUT4AB_ConfigMem.v"

  - name: "run_legacy_1.3_vhdl_demo"
    path: "./legacy/clean/demo_vhdl/"
    language: "vhdl"
    test_mode: "run"
    description: "Run legacy FABulous 1.3 VHDL demo project for error checking"
    expected_outputs:
      - "Fabric/eFPGA_top.vhdl"
      - "Fabric/eFPGA.vhdl"
      - "Tile/LUT4AB/LUT4AB.vhdl"
      - "Tile/LUT4AB/LUT4AB_switch_matrix.csv"
      - "Tile/LUT4AB/LUT4AB_switch_matrix.vhdl"
      - "Tile/LUT4AB/LUT4AB_ConfigMem.csv"
      - "Tile/LUT4AB/LUT4AB_ConfigMem.vhdl"

  # We can only check for bitstream spec, pips.txt. and bel.txt and so on here, since the RTL generation changed a lot
  # but should be still logically equal.
  - name: "diff_legacy_1.3_verilog_reference_demo"
    path: "./legacy/reference/demo_verilog/"
    language: "verilog"
    test_mode: "diff"
    description: "Run and diff legacy FABulous v1.3 project for backward compatibility testing"
    include_patterns:
     - "*.csv"
     - "*.txt"
    exclude_patterns:
     - "eFPGA_geometry.csv"

  # We can only check for bitstream spec, pips.txt. and bel.txt and so on here, since the RTL generation changed a lot
  # but should be still logically equal.
  - name: "diff_legacy_1.3_vhdl_reference_demo"
    path: "./legacy/reference/demo_vhdl/"
    language: "vhdl"
    test_mode: "diff"
    description: "Run and diff legacy FABulous v1.3 project for backward compatibility testing"
    include_patterns:
     - "*.csv"
     - "*.txt"
    exclude_patterns:
     - "eFPGA_geometry.csv"

